---
title: "Cantones de Costa Rica"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r carga de paquetes}
library(dplyr)
library(sf)
library(leaflet)
library(DT)
library(tidyverse)
library(ggplot2)
library(plotly)
```

```{r lectura de datos}
cantones <- 
  st_read(dsn = "cantones_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)

```


Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}
leaflet() %>%
  addTiles(group = "OpenStreetMap") %>%
  addPolygons(data = cantones, weight = 1.0) %>%
  addLayersControl(baseGroups = c("OpenStreetMap"),
                   overlayGroups = c("Cantones"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
cantones %>%
  dplyr::select(provincia, canton, area) %>%
  datatable(colnames = c(
    "provincia", "canton", "area"
    
  ), options = list(pageLength = 5, language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')))
```

### Chart C

```{r}
cantones_grafico <-
cantones %>%
  slice_max(area, n = 8) %>%
  st_drop_geometry() %>%
  ggplot(aes (x = reorder (canton, area), y = area)) + 
  geom_bar(stat = "identity") +
coord_flip() +
ggtitle("Area de cada canton") + 
  xlab("canton") + 
  ylab("area") + 
  theme_minimal()

ggplotly(cantones_grafico) %>% 
  config(locale = 'es')
```

